package merger

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"reflect"
	"strings"
	"testing"
)

var completeTestFile []byte = []byte(`// Source: ./xxxx/xxxx (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package mock_test -destination=mocks/mock_repository.go ./xxxx/xxxx Repository
//

// Package mock_test is a generated GoMock package.
package mock_test

import (
	context "context"
	reflect "reflect"

	repository "github.com/xxxx/xxxx/xxxx/xxxx/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder[T]
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder[T any] struct {
	mock *MockRepository[T]
}

// NewMockRepository creates a new mock instance.
func NewMockRepository[T any](ctrl *gomock.Controller) *MockRepository[T] {
	mock := &MockRepository[T]{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository[T]) EXPECT() *MockRepositoryMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository[T]) Create(arg0 context.Context, arg1 T, arg2 repository.Compare[T]) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder[T]) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository[T])(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockRepository[T]) Delete(arg0 context.Context, arg1 uint64) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder[T]) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository[T])(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockRepository[T]) FindAll(arg0 context.Context) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder[T]) FindAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository[T])(nil).FindAll), arg0)
}

// FindByID mocks base method.
func (m *MockRepository[T]) FindByID(arg0 context.Context, arg1 uint64) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder[T]) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository[T])(nil).FindByID), arg0, arg1)
}

// FindFilterFunc mocks base method.
func (m *MockRepository[T]) FindFilterFunc(arg0 context.Context, arg1 repository.Filter[T]) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFilterFunc", arg0, arg1)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFilterFunc indicates an expected call of FindFilterFunc.
func (mr *MockRepositoryMockRecorder[T]) FindFilterFunc(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFilterFunc", reflect.TypeOf((*MockRepository[T])(nil).FindFilterFunc), arg0, arg1)
}

// Update mocks base method.
func (m *MockRepository[T]) Update(arg0 context.Context, id uint64, in T, fnd repository.Compare[T]) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, id, in, fnd)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder[T]) Update(arg0, id, in, fnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository[T])(nil).Update), arg0, id, in, fnd)
}`)

func TestNewMerger(t *testing.T) {
	v := NewMerger()
	r := reflect.ValueOf(v)
	if _, ok := reflect.TypeAssert[Merger](r); !ok {
		t.Fatalf(`err1`)
	}
	if _, ok := reflect.TypeAssert[*merger](r); !ok {
		t.Fatalf(`err2`)
	}

	new := &merger{
		imports: make(map[string]imprt, 15),
	}
	if !reflect.DeepEqual(v, new) {
		t.Fatalf(`err3`)
	}
}

func TestSetPackage(t *testing.T) {
	tc := []struct {
		in  string
		out string
	}{
		{"lower", "lower"},
		{"UPPER", "UPPER"},
		{"MiXeD", "MiXeD"},
		{"Spécial_%!@🙃", "Spécial_%!@🙃"},
	}

	for _, test := range tc {
		t.Run(test.in, func(t *testing.T) {
			m := NewMerger()
			m.SetPackage(test.in)
			cast, ok := m.(*merger)
			if !ok {
				t.Fatalf("could not cast Merger to *merger")
			}
			if !reflect.DeepEqual(cast.pkgName, test.out) {
				t.Fatalf(`value was not expected for input "%v". Expected %v, got %v`, test.in, test.out, cast.pkgName)
			}
		})
	}
}

func TestWrite(t *testing.T) {
	type inout struct {
		in  []byte
		out int
		err error
	}

	tc := map[string]struct {
		inout   []inout
		docbuf  bytes.Buffer
		pkgName string
		imports map[string]imprt
		bodybuf bytes.Buffer
	}{
		"empty": {
			[]inout{
				{
					[]byte(``),
					0,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
			"",
			map[string]imprt{},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
		},
		"[one] package only uppercase": {
			[]inout{
				{
					[]byte(`package UPPER`),
					0,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
			"UPPER",
			map[string]imprt{},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
		},
		"[one] package with one line import": {
			[]inout{
				{
					[]byte(`package pkg
import "math"`),
					0,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
			"pkg",
			map[string]imprt{
				`"math"`: {
					"",
					`"math"`,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
		},
		"[one] package with multiple line import": {
			[]inout{
				{
					[]byte(`package pkg
import _ "math"
import . "custom/path/package"`),
					0,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
			"pkg",
			map[string]imprt{
				`"math"`: {
					"_",
					`"math"`,
				},
				`"custom/path/package"`: {
					".",
					`"custom/path/package"`,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
		},
		"[one] package with imports": {
			[]inout{
				{
					[]byte(`package pkg
import (
"math"
"fmt"
)`),
					0,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
			"pkg",
			map[string]imprt{
				`"math"`: {
					"",
					`"math"`,
				},
				`"fmt"`: {
					"",
					`"fmt"`,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
		},
		"[one] pkg doc with package with imports": {
			[]inout{
				{
					[]byte(`//string doc
package pkg
import (
"math"
"fmt"
)`),
					13,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				tmp.WriteString("//string doc\n")
				return tmp
			}(),
			"pkg",
			map[string]imprt{
				`"math"`: {
					"",
					`"math"`,
				},
				`"fmt"`: {
					"",
					`"fmt"`,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				return tmp
			}(),
		},
		"[one] pkg doc with package with imports & body": {
			[]inout{
				{
					[]byte(`//string doc
package pkg
import (
"math"
"fmt"
)
body is not necessary valid go`),
					79,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				tmp.WriteString("//string doc\n")
				return tmp
			}(),
			"pkg",
			map[string]imprt{
				`"math"`: {
					"",
					`"math"`,
				},
				`"fmt"`: {
					"",
					`"fmt"`,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				tmp.WriteString("body is not necessary valid go")
				return tmp
			}(),
		},
		"[multiple] 3 small files": {
			[]inout{
				{
					[]byte(`// multi
// line
// string
// doc
package pkg1
import (
"fmt"
)

func main() {
fmt.Println("Hello World !")
}`),
					109,
					nil,
				},
				{
					[]byte(`package pkg2
import (
"math"
"fmt"
)

func main() {
fmt.Println(math.Pi)
}
`),
					75,
					nil,
				},
				{
					[]byte(`// more doc
package pkg3
import (
"log"
"maps"
"math"
)

func main() {
for v := range maps.Values(map[string]float64{"": 38.5}) {
log.Println(math.Round(v))
}
}
`),
					161,
					nil,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				tmp.WriteString(`// multi
// line
// string
// doc

// more doc
`)
				return tmp
			}(),
			"pkg1",
			map[string]imprt{
				`"fmt"`: {
					"",
					`"fmt"`,
				},
				`"log"`: {
					"",
					`"log"`,
				},
				`"math"`: {
					"",
					`"math"`,
				},
				`"maps"`: {
					"",
					`"maps"`,
				},
			},
			func() bytes.Buffer {
				var tmp bytes.Buffer
				tmp.WriteString(`func main() {
fmt.Println("Hello World !")
}
func main() {
fmt.Println(math.Pi)
}

func main() {
for v := range maps.Values(map[string]float64{"": 38.5}) {
log.Println(math.Round(v))
}
}
`)
				return tmp
			}(),
		},
	}

	for name, test := range tc {
		t.Run(name, func(t *testing.T) {
			m := NewMerger()
			for _, tst := range test.inout {
				v, err := m.Write(tst.in)
				if !reflect.DeepEqual(v, tst.out) {
					t.Fatalf(`wrong number of bytes written. Expected %v, got %v`, tst.out, v)
				}
				if err != nil && !errors.Is(err, tst.err) {
					t.Fatalf(`unexpected error. Expected %v, got %v`, tst.err, err)
				}
			}

			cast, ok := m.(*merger)
			if !ok {
				t.Fatalf("could not cast Merger to *merger")
			}

			if !reflect.DeepEqual(cast.docbuf, test.docbuf) {
				t.Fatalf(`docubuf value error. Expected %v, got %v`, test.docbuf, cast.docbuf)
			}
			if !reflect.DeepEqual(cast.pkgName, test.pkgName) {
				t.Fatalf(`pkgName value error. Expected %v, got %v`, test.pkgName, cast.pkgName)
			}
			if !reflect.DeepEqual(cast.imports, test.imports) {
				t.Fatalf(`imports value error. Expected %v, got %v`, test.imports, cast.imports)
			}
			if !reflect.DeepEqual(cast.bodybuf, test.bodybuf) {
				t.Fatalf(`bodybuf value error. Expected %v, got %v`, test.bodybuf, cast.bodybuf)
			}
		})
	}
}

func TestWriteTo(t *testing.T) {
	t.Run("normal cases", func(t *testing.T) {
		tc := map[string]struct {
			docbuf   bytes.Buffer
			pkgName  string
			imports  map[string]imprt
			bodybuf  bytes.Buffer
			out      int64
			err      error
			expected string
		}{
			"empty (with package name cause cannot test if empty)": {
				func() bytes.Buffer {
					var tmp bytes.Buffer
					return tmp
				}(),
				// cannot test if empty, causes to write `package `
				// but cannot use trailing space in go string for test
				"name",
				map[string]imprt{},
				func() bytes.Buffer {
					var tmp bytes.Buffer
					return tmp
				}(),
				14,
				nil,
				`package name

`,
			},
			"with docstring": {
				func() bytes.Buffer {
					var tmp bytes.Buffer
					tmp.WriteString(`// this
// is
// doc
// string
`)
					return tmp
				}(),
				// cannot test if empty, causes to write `package `
				// but cannot use trailing space in go string for test
				"name",
				map[string]imprt{},
				func() bytes.Buffer {
					var tmp bytes.Buffer
					return tmp
				}(),
				45,
				nil,
				`// this
// is
// doc
// string
package name

`,
			},
			"with body": {
				func() bytes.Buffer {
					var tmp bytes.Buffer
					return tmp
				}(),
				// cannot test if empty, causes to write `package `
				// but cannot use trailing space in go string for test
				"name",
				map[string]imprt{},
				func() bytes.Buffer {
					var tmp bytes.Buffer
					tmp.WriteString(`random body
`)
					return tmp
				}(),
				26,
				nil,
				`package name

random body
`,
			},
			"with imports": {
				func() bytes.Buffer {
					var tmp bytes.Buffer
					return tmp
				}(),
				// cannot test if empty, causes to write `package `
				// but cannot use trailing space in go string for test
				"name",
				map[string]imprt{
					`"fmt"`: {
						".",
						`"fmt"`,
					},
					`"math"`: {
						"_",
						`"math"`,
					},
					`"maps"`: {
						"",
						`"maps"`,
					},
					`"path/to/package"`: {
						"pkg",
						`"path/to/package"`,
					},
				},
				func() bytes.Buffer {
					var tmp bytes.Buffer
					return tmp
				}(),
				76,
				nil,
				`package name

import (
	. "fmt"
	"maps"
	_ "math"
	pkg "path/to/package"
)

`,
			},
			"a bit of everything": {
				func() bytes.Buffer {
					var tmp bytes.Buffer
					tmp.WriteString(`// doc1

// doc2
// doc2

// doc3
`)
					return tmp
				}(),
				// cannot test if empty, causes to write `package `
				// but cannot use trailing space in go string for test
				"name",
				map[string]imprt{
					`"fmt"`: {
						".",
						`"fmt"`,
					},
					`"math"`: {
						"_",
						`"math"`,
					},
					`"maps"`: {
						"",
						`"maps"`,
					},
					`"path/to/package"`: {
						"pkg",
						`"path/to/package"`,
					},
				},
				func() bytes.Buffer {
					var tmp bytes.Buffer
					tmp.WriteString(`func main() {
fmt.Println("Hello World !")
}

func main() {
fmt.Println(math.Pi)
}

func main() {
for v := range maps.Values(map[string]float64{"": 38.5}) {
log.Println(math.Round(v))
}
}
`)
					return tmp
				}(),
				298,
				nil,
				`// doc1

// doc2
// doc2

// doc3
package name

import (
	. "fmt"
	"maps"
	_ "math"
	pkg "path/to/package"
)

func main() {
fmt.Println("Hello World !")
}

func main() {
fmt.Println(math.Pi)
}

func main() {
for v := range maps.Values(map[string]float64{"": 38.5}) {
log.Println(math.Round(v))
}
}
`,
			},
		}

		for name, test := range tc {
			t.Run(name, func(t *testing.T) {
				m := NewMerger()

				cast, ok := m.(*merger)
				if !ok {
					t.Fatalf("could not cast Merger to *merger")
				}
				cast.docbuf = test.docbuf
				cast.pkgName = test.pkgName
				cast.imports = test.imports
				cast.bodybuf = test.bodybuf

				var buf strings.Builder
				v, err := m.WriteTo(&buf)
				if !reflect.DeepEqual(v, test.out) {
					t.Fatalf(`wrong number of bytes written. Expected %v, got %v`, test.out, v)
				}
				if err != nil && !errors.Is(err, test.err) {
					t.Fatalf(`unexpected error. Expected %v, got %v`, test.err, err)
				}

				out := buf.String()
				if !reflect.DeepEqual(out, test.expected) {
					t.Fatalf(`wrong output. Expected "%v", got "%v"`, test.expected, out)
				}
			})
		}
	})

	t.Run("err cases", func(t *testing.T) {
		tc := map[string]struct {
			f     []byte
			limit int64
			out   int64
			err   error
		}{
			"err doc write, no write": {
				completeTestFile,
				0,
				0,
				ErrMaximumWrite,
			},
			"err package write": {
				completeTestFile,
				232,
				231,
				ErrMaximumWrite,
			},
			"err package name write": {
				completeTestFile,
				240,
				239,
				ErrMaximumWrite,
			},
			"err line return after package write": {
				completeTestFile,
				250,
				248,
				ErrMaximumWrite,
			},
			"err import write": {
				completeTestFile,
				252,
				250,
				ErrMaximumWrite,
			},
			"err \t write": {
				completeTestFile,
				260,
				259,
				ErrMaximumWrite,
			},
			"err import name write": {
				completeTestFile,
				262,
				260,
				ErrMaximumWrite,
			},
			"err import space between name & path write": {
				completeTestFile,
				268,
				267,
				ErrMaximumWrite,
			},
			"err import path write": {
				completeTestFile,
				270,
				268,
				ErrMaximumWrite,
			},
			"err import \n write": {
				completeTestFile,
				278,
				277,
				ErrMaximumWrite,
			},
			"err \n\n after import write": {
				completeTestFile,
				389,
				387,
				ErrMaximumWrite,
			},
			"err body write": {
				completeTestFile,
				450,
				390,
				ErrMaximumWrite,
			},
		}

		for name, test := range tc {
			t.Run(name, func(t *testing.T) {
				m := NewMerger()
				m.Write(test.f)

				var buf strings.Builder
				w := NewLimitWriter(&buf, test.limit)
				// w := NewLimitWriter(new(strings.Builder), test.limit)
				v, err := m.WriteTo(w)
				if !reflect.DeepEqual(v, test.out) {
					fmt.Printf("buf.String() | %T | %v\n", buf.String(), buf.String())
					t.Fatalf(`wrong number of bytes written. Expected %v, got %v`, test.out, v)
				}
				if err != nil && !errors.Is(err, test.err) {
					t.Fatalf(`unexpected error. Expected %v, got %v`, test.err, err)
				}
			})
		}
	})
}

// Copy k8s.io/kubernetes/pkg/util/limitwriter as we
// only need limitwriter and do not want all kube package

/*
Copyright 2015 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// NewLimitWriter creates a writer that is limited to writing at most n
// bytes to w. This writer is not thread safe.
func NewLimitWriter(w io.Writer, n int64) io.Writer {
	return &limitWriter{
		w: w,
		n: n,
	}
}

// ErrMaximumWrite is returned when all bytes have been written.
var ErrMaximumWrite = errors.New("maximum write")

type limitWriter struct {
	w io.Writer
	n int64
}

func (w *limitWriter) Write(p []byte) (n int, err error) {
	if int64(len(p)) > w.n {
		p = p[:w.n]
	}
	if w.n > 0 {
		n, err = w.w.Write(p)
		w.n -= int64(n)
	}
	if w.n == 0 {
		err = ErrMaximumWrite
	}
	return
}
