// Source: ./xxxx/xxxx (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -package mock_test -destination=mocks/mock_repository.go ./xxxx/xxxx Repository
//

// Package mock_test is a generated GoMock package.
package mock_test

import (
	context "context"
	reflect "reflect"

	repository "github.com/xxxx/xxxx/xxxx/xxxx/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder[T]
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder[T any] struct {
	mock *MockRepository[T]
}

// NewMockRepository creates a new mock instance.
func NewMockRepository[T any](ctrl *gomock.Controller) *MockRepository[T] {
	mock := &MockRepository[T]{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository[T]) EXPECT() *MockRepositoryMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepository[T]) Create(arg0 context.Context, arg1 T, arg2 repository.Compare[T]) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder[T]) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository[T])(nil).Create), arg0, arg1, arg2)
}

// Delete mocks base method.
func (m *MockRepository[T]) Delete(arg0 context.Context, arg1 uint64) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder[T]) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository[T])(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockRepository[T]) FindAll(arg0 context.Context) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockRepositoryMockRecorder[T]) FindAll(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockRepository[T])(nil).FindAll), arg0)
}

// FindByID mocks base method.
func (m *MockRepository[T]) FindByID(arg0 context.Context, arg1 uint64) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockRepositoryMockRecorder[T]) FindByID(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockRepository[T])(nil).FindByID), arg0, arg1)
}

// FindFilterFunc mocks base method.
func (m *MockRepository[T]) FindFilterFunc(arg0 context.Context, arg1 repository.Filter[T]) ([]T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFilterFunc", arg0, arg1)
	ret0, _ := ret[0].([]T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFilterFunc indicates an expected call of FindFilterFunc.
func (mr *MockRepositoryMockRecorder[T]) FindFilterFunc(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFilterFunc", reflect.TypeOf((*MockRepository[T])(nil).FindFilterFunc), arg0, arg1)
}

// Update mocks base method.
func (m *MockRepository[T]) Update(arg0 context.Context, id uint64, in T, fnd repository.Compare[T]) (T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, id, in, fnd)
	ret0, _ := ret[0].(T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRepositoryMockRecorder[T]) Update(arg0, id, in, fnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepository[T])(nil).Update), arg0, id, in, fnd)
}
